# Generated by Django 3.0.1 on 2020-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0015_auto_20200430_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
