# Generated by Django 3.0.1 on 2020-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0018_auto_20200430_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='/media/default.jpg', upload_to='profilepics/'),
        ),
    ]
