# Generated by Django 3.0.1 on 2020-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0019_auto_20200430_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(upload_to='profilepics/'),
        ),
    ]
