# Generated by Django 3.0.1 on 2020-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0020_auto_20200430_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
