# Generated by Django 3.0.1 on 2020-04-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0021_auto_20200430_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='/media/default.jpg', upload_to='profilepics/'),
        ),
    ]
