# Generated by Django 3.0.1 on 2020-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0024_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='profilepics/82401_jI9CG7R.jpg', upload_to='profilepics/'),
        ),
    ]
