# Generated by Django 3.0.1 on 2020-05-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0028_auto_20200501_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(upload_to='profilepics/'),
        ),
    ]
