# Generated by Django 3.0.1 on 2020-05-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0029_auto_20200502_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('postpic', models.ImageField(upload_to='postpics/')),
                ('postcaption', models.CharField(max_length=100)),
                ('posttime', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaroid.User')),
            ],
        ),
    ]
