# Generated by Django 3.0.1 on 2020-05-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0031_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
