# Generated by Django 3.0.1 on 2020-05-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0032_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.BooleanField(default=False)),
                ('request_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='polaroid.User')),
                ('request_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='polaroid.User')),
            ],
        ),
    ]
