# Generated by Django 3.0.1 on 2020-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0033_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
