# Generated by Django 3.0.1 on 2020-05-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0034_friend_request_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_from_r', to='polaroid.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='request_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_to_r', to='polaroid.User'),
        ),
    ]
