# Generated by Django 3.0.1 on 2020-05-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0035_auto_20200508_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request_to',
        ),
        migrations.AddField(
            model_name='friend',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='polaroid.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='polaroid.User'),
        ),
    ]
