# Generated by Django 3.0.1 on 2020-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0038_auto_20200514_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='postid',
        ),
        migrations.AddField(
            model_name='like',
            name='postid',
            field=models.ManyToManyField(to='polaroid.Post'),
        ),
    ]
