# Generated by Django 3.0.1 on 2020-05-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0039_auto_20200514_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='polaroid.User'),
        ),
    ]
