# Generated by Django 3.0.1 on 2020-05-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0040_like_post_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
