# Generated by Django 3.0.1 on 2020-05-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0042_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='postid',
        ),
        migrations.AddField(
            model_name='like',
            name='postid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polaroid.Post'),
        ),
    ]
