# Generated by Django 3.0.1 on 2020-05-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0044_auto_20200515_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
