# Generated by Django 3.0.1 on 2020-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0045_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='polaroid.User'),
        ),
    ]
