# Generated by Django 3.0.1 on 2020-05-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0046_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaroid.Post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaroid.User')),
            ],
        ),
    ]
