# Generated by Django 3.0.1 on 2020-05-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0047_auto_20200516_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100, null=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaroid.Post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaroid.User')),
            ],
        ),
    ]
