# Generated by Django 3.0.1 on 2020-05-18 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0049_auto_20200518_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 17, 14, 39, 891869)),
        ),
    ]
