# Generated by Django 3.0.1 on 2020-05-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0051_auto_20200518_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 36, 3, 848745)),
        ),
    ]
