# Generated by Django 3.0.1 on 2020-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0054_auto_20200518_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
