# Generated by Django 3.0.1 on 2020-05-18 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0055_auto_20200518_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 20, 3, 28, 916615)),
        ),
    ]
