# Generated by Django 3.0.1 on 2020-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0059_auto_20200519_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
