# Generated by Django 3.0.1 on 2020-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0060_auto_20200519_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
