# Generated by Django 3.1.2 on 2020-10-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroid', '0061_auto_20200519_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
